FROM n8nio/n8n:1.26.0

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=yourpassword
ENV N8N_HOST=n8n.onrender.com
ENV WEBHOOK_TUNNEL_URL=https://n8n.onrender.com
EXPOSE 5678
